//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace centriq_dec_2015_site2.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogPost
    {
        public int BlogPostID { get; set; }
        public int BlogAuthorID { get; set; }
        public string Content { get; set; }
        public System.DateTime PostDate { get; set; }
        public int BlogID { get; set; }
        public string Title { get; set; }
    
        public virtual Blog Blog { get; set; }
        public virtual BlogAuthor BlogAuthor { get; set; }
    }
}
